### ISSUE TITLE
How to sort the cloud modules?

### ISSUE THREAD

**Issue by ovizii** [ya0211/MRepo#27] opened 2023-05-28 09:38 UTC
It looks like they are sorted by name, am I missing something or is there no way to sort by say last updated?

**Comment by ya0211** [comment] 2023-05-28 09:45
Duplicate of #22

**Closed** 2023-05-28 09:47 UTC
Labels: duplicate

**Comment by ovizii** [comment] 2023-05-28 09:54
Sorry about that, I searched your issues for the word "sort" and didn't find the linked issue since it only talks about filtering 😅

**Comment by ya0211** [comment] 2023-05-28 09:57
That's ok, thanks for your interest in MRepo.
